language: php

services:
  - docker

git:
  submodules: false

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - git clone https://github.com/dentalsleepsolutions/dentalsleepsolutions.git
  - cd dentalsleepsolutions/docker
  - cp .env.example .env
  - sed -i "s/^FILE_STORAGE/#FILE_STORAGE/g" .env
  - sed -i "s/^GITHUB_USER/#GITHUB_USER/g" .env
  - sed -i "s/^GITHUB_TOKEN/#GITHUB_TOKEN/g" .env
  - docker-compose build
  - docker-compose up -d
  - docker-compose exec api php artisan passport:keys

script:
  - ./tests.sh
  
